src/Rova/QCMBundle/Entity/Guest.php
<?php

namespace Rova\QCMBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Guest
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Rova\QCMBundle\Entity\GuestRepository")
 */
class Guest
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nickname", type="string", length=255, nullable=true)
     */
    private $nickname;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_created", type="date")
     */
    private $dateCreated;
    
    /**
     * @var string
     *
     * @ORM\Column(name="ip_adress", type="string")
     */
    private $ip_adress;    
    
    /**
     * @ORM\OneToMany(targetEntity="Rova\QCMBundle\Entity\GuestAnswer", mappedBy="guest"
     * , cascade={"persist", "remove"})
     */
    private $answers;
    
    private $score;    
    
    
    /**
     * Constructor
     */
    public function __construct()
    {
        //$this->dateCreated = \DateTime();
        $this->ip_adress = $_SERVER['REMOTE_ADDR'];
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nickname
     *
     * @param string $nickname
     * @return Guest
     */
    public function setNickname($nickname)
    {
        $this->nickname = $nickname;
    
        return $this;
    }

    /**
     * Get nickname
     *
     * @return string 
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Set dateCreated
     *
     * @param \DateTime $dateCreated
     * @return Guest
     */
    public function setDateCreated($dateCreated)
    {
        $this->dateCreated = $dateCreated;
    
        return $this;
    }

    /**
     * Get dateCreated
     *
     * @return \DateTime 
     */
    public function getDateCreated()
    {
        return $this->dateCreated;
    }

    /**
     * Add answers
     *
     * @param \Rova\QCMBundle\Entity\GuestAnswer $answers
     * @return Guest
     */
    public function addAnswer(\Rova\QCMBundle\Entity\GuestAnswer $answers)
    {
        $this->answers[] = $answers;
    
        return $this;
    }

    /**
     * Remove answers
     *
     * @param \Rova\QCMBundle\Entity\GuestAnswer $answers
     */
    public function removeAnswer(\Rova\QCMBundle\Entity\GuestAnswer $answers)
    {
        $this->answers->removeElement($answers);
    }

    /**
     * Get answers
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAnswers()
    {
        return $this->answers;
    }
    
    public function setScore( $score )
    {
        $this->score = $score;
        return $this;
    }
    
    public function getScore()
    {
        return $this->score;
    }    

    /**
     * Set ip_adress
     *
     * @param string $ipAdress
     * @return Guest
     */
    public function setIpAdress($ipAdress)
    {
        $this->ip_adress = $ipAdress;
    
        return $this;
    }

    /**
     * Get ip_adress
     *
     * @return string 
     */
    public function getIpAdress()
    {
        return $this->ip_adress;
    }
}

src/Rova/QCMBundle/Entity/Question.php
<?php

namespace Rova\QCMBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Question
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Rova\QCMBundle\Entity\QuestionRepository")
 */
class Question
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /** 
     * @ORM\ManyToOne(targetEntity="Rova\QCMBundle\Entity\Serie", inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $serie;
    
    /**
     * @var string
     *
     * @ORM\Column(name="questionLabel", type="string", length=255)
     */
    private $questionLabel;    
    
    /**
     * @var string
     *
     * @ORM\Column(name="text", type="string", length=255)
     */
    private $text;
        
    /**
     * @var boolean
     *
     * @ORM\Column(name="multipleChoice", type="boolean")
     */
    private $multipleChoice;
    
    /**
     * @ORM\OneToMany(targetEntity="Rova\QCMBundle\Entity\Choice", mappedBy="question", 
     * cascade={"persist", "remove"})
     */
    private $choices;
    
    

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set questionLabel
     *
     * @param string $questionLabel
     * @return Question
     */
    public function setQuestionLabel($questionLabel)
    {
        $this->questionLabel = $questionLabel;
    
        return $this;
    }

    /**
     * Get questionLabel
     *
     * @return string 
     */
    public function getQuestionLabel()
    {
        return $this->questionLabel;
    }

    /**
     * Set serie
     *
     * @param \Rova\QCMBundle\Entity\Serie $serie
     * @return Question
     */
    public function setSerie(\Rova\QCMBundle\Entity\Serie $serie)
    {
        $this->serie = $serie;
    
        return $this;
    }

    /**
     * Get serie
     *
     * @return \Rova\QCMBundle\Entity\Serie 
     */
    public function getSerie()
    {
        return $this->serie;
    }

    /**
     * Set text
     *
     * @param string $text
     * @return Question
     */
    public function setText($text)
    {
        $this->text = $text;
    
        return $this;
    }

    /**
     * Get text
     *
     * @return string 
     */
    public function getText()
    {
        return $this->text;
    }
    
    public function getTextEscaped()
    {
        return str_replace(array("\n", "\r", ' '), array('</br>', '', '&nbsp;'), htmlentities($this->text));
    }
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->choices = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add choices
     *
     * @param \Rova\QCMBundle\Entity\Choice $choices
     * @return Question
     */
    public function addChoice(\Rova\QCMBundle\Entity\Choice $choice)
    {
        $this->choices[] = $choice;
        $choice->setQuestion($this);
        return $this;
    }

    /**
     * Remove choices
     *
     * @param \Rova\QCMBundle\Entity\Choice $choices
     */
    public function removeChoice(\Rova\QCMBundle\Entity\Choice $choice)
    {
        $this->choices->removeElement($choice);
    }

    /**
     * Get choices
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getChoices()
    {
        return $this->choices;
    }

    /**
     * Set multipleChoice
     *
     * @param boolean $multipleChoice
     * @return Question
     */
    public function setMultipleChoice($multipleChoice)
    {
        $this->multipleChoice = $multipleChoice;
    
        return $this;
    }

    /**
     * Get multipleChoice
     *
     * @return boolean 
     */
    public function getMultipleChoice()
    {
        return $this->multipleChoice;
    }
}

src/Rova/QCMBundle/Resources/views/Guest/QSerie/answer_question_serie.html.twig
{% extends "RovaQCMBundle:Guest:guestLayout.html.twig" %}

{% block rovaqcm_body %}
    <div class="well">
        <h3 id="gogo">{{ serie.serieName }}</h3>
        
        <hr>

        {% for message in app.session.flashbag.get('info_ans') %}
            <p class="text-error">{{ message }}</p>
        {% endfor %}   
        
        <form action="{{ path('rovaqcm_guest_answer_qserie', {'id': serie.id}) }}" method="POST">            
            <ul class="nav-pills nav-stacked">
                {% for question in serie.questions %}
                <li>
                    <strong>{{ question.questionLabel }}</strong>
                    <p>{{ question.textEscaped|raw }}</p>
                    {% if question.multipleChoice %}
                    <ul>
                        {% for choice in question.choices %}
                        <li><label style="background-color: #ddffee;"><input type="checkbox" name="chk[{{ question.id }}][{{ choice.id }}]" value="{{ choice.id }}"/> {{ choice.choiceText }}</label></li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <ul>
                        {% for choice in question.choices %}
                        <li><label style="background-color: #ddffee;"><input type="radio" name="rdo[{{ question.id }}]" value="{{ choice.id }}"/> {{ choice.choiceText }}</label></li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </li>
                {% endfor %}
        	</ul> 
            
            <input type="submit" class="btn btn-primary" value="Valider"/>
        </form>
    </div>

{% endblock %}

src/Rova/QCMBundle/Resources/views/Guest/QSerie/view_question_serie_description.html.twig
{% extends "RovaQCMBundle:Guest:guestLayout.html.twig" %}

{% block rovaqcm_body %}
    <div class="well">
        <h3 id="gogo">{{ serie.serieName }}</h3>
        de {{ serie.user.login }} <br /><br />
        
        {% for categorie in serie.categories %}
            {% if loop.index == 1 %}Catégorie : {% endif %}{{ categorie.name }}{% if loop.revindex > 1 %},{% endif %}
        {% endfor %}
        
        <br />
        
        <hr>

        {% if serie.questions|length == 1 %}
            Le titre de la question
        {% elseif serie.questions|length > 1 %}
            Les titres des questions
        {% endif %}
        <ul>
            {% for question in serie.questions %}
            <li>
               {{ question.questionLabel }}
            </li>
            {% else %}
            <br /><p>Aucune question</p>
            {% endfor %}
    	</ul> 
        
        <a href="{{ path('rovaqcm_guest_answer_qserie', {'id': serie.id}) }}" class="btn btn-primary">Répondre aux questions</a>
        {% if nb_ans > 0 %}
            <a href="{{ path('rovaqcm_guest_view_scores_in_serie_id', {'id': serie.id}) }}" class="btn">Voir qui ont répondu à cette série</a>
        {% endif %}
    </div>
{% endblock %}

src/Rova/QCMBundle/Resources/views/Guest/QSerie/view_question_serie_list.html.twig
{% extends "RovaQCMBundle:Guest:guestLayout.html.twig" %}

{% block rovaqcm_body %} 
    <h4>Liste de toutes les séries de questions</h4>
	    
    <table class="table table-bordered table-striped table-hover">
        <thead style="background-color: #0088ff;">
            <tr>
                <th>Série</th>
                <th>Créateur</th>
                <th>réponses utilisateurs</th>
                <th>réponses visiteurs</th>
            </th>
        </thead>
        <tbody>
            {% set p_user = guest|default('') %}

            {% for row in rows %}
            <tr>
                <td><a rel="tooltip" user-name="{{ row.serie.user.login }}" href="{{ path('rovaqcm_guest_view_qserie_desc_by_id', {'id': row.serie.id}) }}" title="{{ row.nb_ans }}">{{ row.serie.serieName }}</a></td>
                <td>{{ row.serie.user.login }}</td>
                <td>{{ row.nb_ans }}</td>
                <td>{{ row.nb_guest_ans }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>  
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        $(function() {
            $('#nav_menu_view_all_qserie_list').attr('class', 'active');
            
            $( '[rel=tooltip]' ).each( function() {
                var n = parseInt($(this).attr('title'));
                var username = $(this).attr('user-name');
                
                if (n == 0)
                {
                    $(this).attr('title', 'aucun utilisateur n\'a encore répondu aux questions de cette série de ' + username);
                }
                else if (n == 1)
                {
                    $(this).attr('title', 'un utilisateur a répondu aux questions de cette série de ' + username);
                }
                else if ( n > 1 )
                {
                    $(this).attr('title', n + ' utilisateurs ont répondu aux questions de cette série de ' + username);
                }
                
                $(this).tooltip(); 
            } );
        });
    </script>
{% endblock %}

src/Rova/QCMBundle/Resources/views/Guest/QSerie/view_self_score_in_serie.html.twig
{% extends "RovaQCMBundle:Guest:guestLayout.html.twig" %}

{% block rovaqcm_body %} 
    <h3>Points obtenu</h3><hr />

    Vous avez obtenu <strong>{{ total_score }} / {{ max_possible_score }}</strong> pour la série de questions : {{ serie.serieName }}.
{% endblock %}

src/Rova/QCMBundle/Resources/views/Guest/QSerie/view_total_scores_in_serie.html.twig
{% extends "RovaQCMBundle:Guest:guestLayout.html.twig" %}

{% block rovaqcm_body %} 
    <h3>Scores obtenus dans la série {{ serie.serieName }}</h3><hr />

    <h4><strong>Noté sur {{ max_possible_score }}</strong></h4> <br /><br />

    {% if users|length > 0 %}
    <table class="table table-bordered table-striped table-hover">
        <thead style="background-color: #0088ff;">
            <tr>
                <th>Utilisateur</th>
                <th>Note</th>
            </th>
        </thead>
        <tbody>
            {% set p_user = user|default('') %}

            {% for user in users %}
            <tr>
                <td>{{ user.firstName|default('') }} {{ user.lastName|default('') }} {% if p_user != '' %}
                {% if user == p_user %}<strong>(vous)</strong>{% endif %}{% endif %}</td>
                <td><strong>{{ user.score }}</strong><br /></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    
    {% if guests|length > 0 %}
        <table class="table table-bordered table-striped table-hover">
            <thead style="background-color: #0088ff;">
                <tr>
                    <th>Visiteur</th>
                    <th>Note</th>
                </th>
            </thead>
            <tbody>
                {% set p_user = guest|default('') %}
    
                {% for user in guests %}
                <tr>
                    <td>{{ user.nickname|default('(aucun pseudo)') }}
                    {% if p_user != '' %}
                        {% if user == p_user %}<strong>(vous)</strong>{% endif %}
                    {% endif %}</td>
                    <td><strong>{{ user.score }}</strong><br /></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <a href="{{ path('rovaqcm_guest_answer_qserie', {'id': serie.id}) }}" class="btn btn-primary">Répondre aux questions</a>
    {% endif %}
{% endblock %}